feat(book_management): introduce the book management concept
Book management is the set of systems and processes to get and categorize books
so it's easy to browse and discover new content. It involves the next actions:

* Automatically index and download metadata of new books.
* Notify the user when a new book is added.
* Monitor the books of an author, and get them once they are released.
* Send books to the e-reader.
* A nice interface to browse the existent library, with the possibility of
    filtering by author, genre, years, tags or series.
* An interface to preview or read the items.
* An interface to rate and review library items.
* An interface to discover new content based on the ratings and item metadata.

I haven't yet found a single piece of software that fulfills all these needs, in the article I tell you about [Readarr](https://readarr.com/), [Calibre-web](https://github.com/janeczku/calibre-web), [calibre]((https://manual.calibre-ebook.com/), [Polar bookself](https://getpolarized.io/), [GCStar](http://www.gcstar.org/), and how they interact with each other.

feat(promql#Generating range vectors from return values in Prometheus queries): Generating range vectors from return values in Prometheus queries.

feat(flask_restplus): Introduce the Flask-RESTPlus library

[Flask-RESTPlus](https://flask-restplus.readthedocs.io/en/stable/) is an
extension for Flask that adds support for quickly building REST APIs,
but I'd use [FastAPI](fastapi.md) instead.

feat(hard_drive_health): Taking care of your hard drives

Hard drives die, so we must be ready for that to happen. There are several
solutions, such as using [RAID](https://en.wikipedia.org/wiki/RAID) to minimize
the impact of a disk loss, but even then, we should monitor the [bad
sectors](https://en.wikipedia.org/wiki/Bad_sector) to see when are our disks
dying.

In the article we talk about [S.M.A.R.T](https://en.wikipedia.org/wiki/S.M.A.R.T.) and how to solve some hard drive problems.

fix(python_snippets#Install default directories and files for a command line program): Install default directories and files for a command line program

I've been trying for a long time to configure `setup.py` to run the required
steps to configure the required directories and files when doing `pip install`
without success.

Finally, I decided that the program itself should create the data once the
`FileNotFoundError` exception is found. That way, you don't penalize the load
time because if the file or directory exists, that code is not run.

feat(flakehell#issues): Latest version is broken

It returns an [ImportError: cannot import name 'MergedConfigParser' from 'flake8.options.config'](https://github.com/flakehell/flakehell/issues/22), wait for the issue to be solved before upgrading.

feat(privileges): Feminist analysis of privileges and rights

Privileges are a group of special structural benefits, social advantages, that a group
holds over another. So they are elements that should be removed from our lives.

Some of the topics included are:

* What's the difference between privilege and right
* [What can we do to fight the privileges?](privileges.md#what-can-we-do-to-fight-the-privileges)

feat(kitty#Scrollback when ssh into a machine doesn't work): Scrollback when ssh into a machine doesn't work

This happens because the kitty terminfo files are not available on the server.
You can ssh in using the following command which will automatically copy the
terminfo files to the server:

```bash
kitty +kitten ssh myserver
```

feat(dynamicdns): Introduce the Dynamic DNS concept

[Dynamic DNS (DDNS)](https://en.wikipedia.org/wiki/Dynamic_DNS) is a method of
automatically updating a name server in the Domain Name Server (DNS), often in
real time, with the active DDNS configuration of its configured hostnames,
addresses or other information.

feat(terraform#conditionals): how to do elif conditionals in terraform

```terraform
locals {
  test = "${ condition ? value : (elif-condition ? elif-value : else-value)}"
}
```

feat(terraform#debugging): how to enable debug traces

You can set the `TF_LOG` environmental variable to one of the log levels
`TRACE`, `DEBUG`, `INFO`, `WARN` or `ERROR` to change the verbosity of the logs.